### ISSUE TITLE
Please tag version 2.0.1

### ISSUE THREAD

**Issue by aufflick** [allegro/swift-junit#18]
Thanks @vi4m for merging my PRs. If you think it's stable enough, it would be great to tag version 2.0.1 so that spm can pull this in with a version tag.

I've verified the change off the `master` branch in my CI.

**Comment by vi4m** [comment]
Sure, I think we're good to go.

**Comment by vi4m** [comment]
Done: https://github.com/allegro/swift-junit/releases/tag/2.1.0
I decided to bump up the major version since we've changed the output file shape a bit.

**Comment by aufflick** [comment]
Ty :) SPM is now pulling the updated branch.
